### ISSUE TITLE
Issue with core.memoize version

### ISSUE THREAD

**Issue by OliverM** [cemerick/friend#116]
Trying to integrate Friend with the Luminus template by including friend in the project.clj dependencies raises a compiler error that complains

... namespace 'clojure.core.memoize' not found ...  

Adding the following to the project.clj works around the issue: 

```
[org.clojure/core.cache "0.6.3"]
[org.clojure/core.memoize "0.5.6" :exclusions [org.clojure/core.cache]]
``` 

It looks like updating the core.memoize version in Friend's dependencies to 0.6.3 should resolve it.

Some detective work [here](https://github.com/yogthos/luminus-template/issues/77) & [here](https://github.com/LightTable/LightTable/issues/794)

**Comment by cemerick** [comment]
Fixed via #124, you can use `[com.cemerick/friend "0.2.2-SNAPSHOT"]` until I cut a final release.
