### ISSUE TITLE
Google OpenID deprecation

### ISSUE THREAD

**Issue by emlyn** [cemerick/friend#117]
Is the OpenID workflow affected by Google's [deprecation of OpenID 2.0](https://developers.google.com/accounts/docs/OpenID)?

I.e. will logging in with a Google account stop working when Google shuts down the OpenID 2.0 service (on April 20th next year according to the [timeline](https://developers.google.com/+/api/auth-migration#timetable))?

If not, are there any existing workflows that will work with Google after this time?

**Comment by cemerick** [comment]
To answer the original question, yes, the discontinuation of Google's OpenId 2.0 endpoint is a pretty big blow to that mechanism in general. There are plenty of other identity providers that support OpenId 2.0, so the existing workflow will remain where it is.

Officially supporting some kind of google login in friend would be great, but I don't have the bandwidth to work on it now. I'd love to see an easy-to-use solution pop up in the community (probably based on [friend-oauth2](https://github.com/ddellacosta/friend-oauth2) as @kenrestivo's prototype seems to). I'll be happy to recommend it if one should emerge.

**Comment by jwhitlark** [comment]
I didn't want to pull in any other dependencies, so I wrote a handler (just for google oath2 + JWT).  A stripped example is available [here](https://gist.github.com/jwhitlark/5dc423485548c31d2c72).  It requires the commons-codex that is already needed by friend-oauth2, but nothing else.

Note that it seems rare at this point for libraries that handle JWT tokens to actually verify the token matches its signature.  The gist above does so.

**Comment by kolov** [comment]
I tried [ddellacosta/friend-oauth2](https://github.com/ddellacosta/friend-oauth2) and it worked fine. It only goes so far to get an access token (different every time) and leaves the user with the task to fetch the real identity.  I wrote a [little demo](https://github.com/kolov/friend-oauth2-google-demo) which retrieves the identity in the credential-fn, though I think it would be better to incorporate this it in the workflow.

**Comment by corey** [comment]
Since we need this in multiple projects, we thought that it might be useful to have it packaged up as a  ready-to-go workflow. We used Google's own libraries to verify the tokens which automatically handles fetching and caching the certs.

We've released it at [Mayvenn/friend-google-openid](https://github.com/Mayvenn/friend-google-openid) so that others won't have to spend hours implementing.

**Comment by cemerick** [comment]
Thanks @corey. Sorry to not recognize your work earlier, but it's important.

Given https://github.com/cemerick/friend/issues/45#issuecomment-270696012, I'm considering this issue closed as of 0.3.0.
