### ISSUE TITLE
The first example in the readme being "wrong"

### ISSUE THREAD

**Issue by kqr** [cemerick/friend#125]
I'm not sure if I'm the only one, but when I saw the first example in the readme I assumed the :credential-fn could go either outside of the :workflow or as an argument to it. Apparently that is not the case at least with basic-http, which requires the :credential-fn as an argument to the workflow. I figured that out after banging my head against the wall one time too many!

Maybe I've misunderstood something, in which case maybe other users have too? If the example is correct, a note that clears that bit up might be useful. I certainly still don't understand it.

**Comment by cemerick** [comment]
The example is correct AFAICT. `:credential-fn` can be provided directly to `authenticate`, or you can provide separate credential functions to individual workflows. Examples of both approaches:

https://github.com/cemerick/friend/blob/master/test/test_friend/mock_app.clj#L119
https://github.com/cemerick/friend/blob/master/test/test_friend/http_basic.clj#L20
