### ISSUE TITLE
Handling multiple authentications with friend and credential-fn

### ISSUE THREAD

**Issue by pate** [cemerick/friend#126]
When a signed-in user authenticates with an additional OAuth provider, I need to conditionally retrieve or create a user entity based on whether they were already signed in. However, I do not have access to the currently signed-in user from the `credential-fn`.

How should I go about dealing with multiple authentications? Perhaps an additional workflow that checks for new friend session data and creates the necessary entities?

**Comment by cemerick** [comment]
If the user is already authenticated, then that identity will be in their ring session. You can easily retrieve it using `com.cemerick/identity` (takes the ring request map).

Getting at the current session from the credential function can be a bit tricky. You can either create your own shim workflow (wrapping whatever friend oauth workflow you have) to directly have access to the request, or you can introduce a dynamic var that you rebind to the current request via a small additional ring middleware.
