### ISSUE TITLE
RunTimeException on Clojure 1.6

### ISSUE THREAD

**Issue by ricardojmendez** [cemerick/friend#127]
After including [com.cemerick/friend "0.2.1"] as a dependency on a Clojure 1.6 application, attempting to run a ring server results in:

Exception in thread "main" java.lang.RuntimeException: No such var: clojure.core.cache/through, compiling:(clojure/core/memoize.clj:52:3)

There are no other changes that could be causing this:

	diff --git a/project.clj b/project.clj
	index 8311541..89c2c49 100644
	--- a/project.clj
	+++ b/project.clj
	@@ -75,6 +75,7 @@
	                  [ring-server "0.3.1"]
	                  [secretary "1.2.1"]
	                  [ragtime "0.3.6"]
	+                 [com.cemerick/friend "0.2.1"]
	                  [im.chit/cronj "1.4.2"]]
	   :repl-options {:init-ns lfg.repl}
	   :min-lein-version "2.0.0")
	\ No newline at end of file

Might be a conflict with another one of the referenced libraries - it's a Luminus project. Will report back if I find more details.

**Comment by cemerick** [comment]
Fixed via #124, you can use `[com.cemerick/friend "0.2.2-SNAPSHOT"]` until I cut a final release.

**Comment by tonygaetani** [comment]
@cemerick any chance you'll get around to cutting a final release of 0.2.2 any time soon?
