### ISSUE TITLE
Google is Depreciating OpenID

### ISSUE THREAD

**Issue by justaboutnormal** [cemerick/friend#134]
Google is depreciating OpenID in favor or OAuth.

**Comment by PetrGlad** [comment]
...deprecating in favor of OpenID Connect. It seems that openid4java is not actively maintained (last source changes were in Spring 2013).
Maybe it's a good idea to use one of 
* http://kit.mit.edu/projects/mitreid-connect
* https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions
* https://oltu.apache.org/

**Comment by sgrimm-sg** [comment]
There is a patch in #117 that might be worth a look.

**Comment by cemerick** [comment]
Closing here to consolidate discussion @ #117.
