### ISSUE TITLE
Turns nil responses into empty maps

### ISSUE THREAD

**Issue by logaan** [cemerick/friend#136]
This code, more or less taken from the example app

```clojure
(friend/authenticate
        {:allow-anon? true
         :login-uri "/login"
         :default-landing-uri "/"
         :unauthorized-handler
         #(-> (hiccup/html
                [:h2 "You do not have sufficient privileges to access "
                 (:uri %)])
              resp/response
              (resp/status 401))
         :credential-fn #(creds/bcrypt-credential-fn @users %)
         :workflows [(workflows/interactive-form)]})
```

Will take a nil response and turn it into a {}. Nil responses in ring mean that there has been no match up to that point. This may not be an issue on it's own but other libraries (such as ring-defaults) see the empty map and decide that a match has been found and make their modifications to the response (like inserting headers). This can turn a response that should be a 404 into a very confusing 200.

Desired behaviour is nil in, nil out.

**Comment by cemerick** [comment]
This is fixed in #115. A snapshot build is available until I cut a final `0.2.2` release: `[com.cemerick/friend "0.2.2-SNAPSHOT"]`.
