### ISSUE TITLE
org.clojure/core.cache dependency / rook compatibility

### ISSUE THREAD

**Issue by mhuebert** [cemerick/friend#143]
Friend 0.2.1 does not work with [rook](/AvisoNovate/rook) due to conflicting `org.clojure/core.cache` dependencies.

I can run the project with `[com.cemerick/friend "0.2.1" :exclusions [org.clojure/core.cache]]` but I don't know if this could cause unintended behavior with friend?

(Using 0.2.2-SNAPSHOT also works, but I'd like to know that I'm using a stable build for authentication.)

**Comment by Frozenlock** [comment]
I had the same kind of problems when trying to use with Figwheel.

Once the core.cache was excluded, I got:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/conn/HttpClientConnectionManager, compiling:(cemerick/pomegranate/aether.clj:42:54)
```

This seems to fix the issue:

```clj
[com.cemerick/friend "0.2.1" :exclusions [org.clojure/core.cache
                                          org.apache.httpcomponents/httpclient]]
```

**Comment by cemerick** [comment]
0.2.2 is out now, so this should be resolved.
