### ISSUE TITLE
Duplicate call to `login-failure-handler` in OpenID workflow?

### ISSUE THREAD

**Issue by JulianKniephoff** [cemerick/friend#149]
When using the OpenID workflow, I noticed that my `:login-failure-handler` gets called twice, Once in `handle-return` and then again, when `:credential-fn` and `:login-failure-handler` return `nil` in the function returned by `workflow`.

Is this expected? If so: How am I supposed to distinguish between these two calls in the `:login-failure-handler`? Specifically, I want to redirect back to the login page, when the login fails, but when I return a ring redirect response in `:login-failure-handler`, the workflow seems to interpret it as a successful authentication map and just ignores the redirection. If I return `nil`, though, so that `handle-return` also returns `nil`, I (of course) won't be redirected either.

I tested this by the way with a `:credential-fn` that always returns `nil`.

**Comment by cemerick** [comment]
"Classic" OpenId support is being nuked from orbit, #45 

If you _actually_ need classic openid support, then reanimating it in a separate workflow-only project is the best option going forward.

Sorry for the lack of response here. :-(
