### ISSUE TITLE
Redirections in Heroku don't work.

### ISSUE THREAD

**Issue by alvatar** [cemerick/friend#153]
The cause might be that Friend might be producing wrong absolute redirect URLs. 
For example:

```
< HTTP/1.1 302 Found
< Connection: keep-alive
< Location: http://af9751f2-5541-49de-9615-ea8.prvt.dyno.rt.heroku.com:80/login
< Server: Aleph/0.4.1
< Date: Sat, 31 Dec 2016 10:37:16 GMT
< Content-Length: 0
< Via: 1.1 vegur
```

This one is performed with cURL. After this request, Heroku invariably replies with "No found app".
If I set the `:login-uri` to the full path instead of `/login`, then it works for the initial (unauthenticated) redirect, but then it won't for the form POST request since I guess that's what's used for the POST route path as well.

I've tried all sorts of combinations of middleware, and made sure I didn't have the `wrap-absolute-redirects` middleware enabled.

**Comment by alvatar** [comment]
The folks at Heroku assured me that they don't do any rewriting of the `Location` header.

**Comment by cemerick** [comment]
`[com.cemerick/friend "0.3.0-SNAPSHOT"]` has been deployed with what I think might fix this. Give it a try and report back.

**Comment by alvatar** [comment]
Works. Thanks a lot for the fix!
